apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
  labels:
    app: {{ .Release.Name }}-nats
spec:
  type: ClusterIP
  ports:
    - port: 4222
      targetPort: 4222
      protocol: TCP
      name: client
    - port: 8222
      targetPort: 8222
      protocol: TCP
      name: monitoring
  selector:
    app: {{ .Release.Name }}-nats