version: "3.5"
services:
  nats:
    image: nats
    ports:
      - ${PORT:-8222}:8222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"
    networks: ["nats"]
  nats-1:
    image: nats
    ports:
      - 4222:4222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    ports:
      - 4223:4222
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]

  prom-exporter:
    image: natsio/prometheus-nats-exporter:latest
    command: "-varz -jsz=all http://nats:8222"
    ports:
      - 7777:7777
    networks:
      - nats
    depends_on:
      - nats

networks:
  nats:
    name: nats
