[package]
name = "escpos-test"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.7", features = ["tracing"] }
env_logger = "0.11.5"
escpos = { version = "0.13.0", features = ["full"] }
tokio = { version = "1.41.0", features = ["macros", "rt-multi-thread"] }
