services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE="Europe/Berlin"
      - TZ="Europe/Berlin"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
    ports:
      - 127.0.0.1:5678:5678
    container_name: n8n

volumes:
  n8n_data:
