apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # This matches the labels from the Deployment
  ports:
    - protocol: TCP
      port: 80 # The Service's port
      targetPort: 80 # The container's port
  # type: ClusterIP # Change to NodePort or LoadBalancer for external access
  type: NodePort
