services:
  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: ./my-app
          target: /usr/src/app
          ignore:
            - node_modules
        - action: rebuild
          path: ./my-app/package.json
  # server:
    # build:
      # context: ./derp
      # dockerfile: Dockerfile
    # ports:
      # - 3000:3000
