apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
spec:
  ports:
    - port: 4222
      name: client
    - port: 6222
      name: cluster
    - port: 8222
      name: monitor
  selector:
    app: nats
  type: ClusterIP # Change to LoadBalancer if needed
