services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80   # Expose port 80 to the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount your custom nginx.conf file
    network_mode: host

