[package]
name = "appmixer-pw-gen"
version = "0.1.0"
authors = ["Joxtacy <10127673+Joxtacy@users.noreply.github.com>"]
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.26.0"
redis = "0.25.4"
tui-tree-widget = "0.20.0"
